name: GlitchSMP
version: '1.0-SNAPSHOT'
main: org.nu11ified.glitchSMP.GlitchSMP
api-version: '1.21'
load: STARTUP
softdepend: [WorldGuard]
authors: [ Nu11ified @ Github ]
description: "A plugin that adds glitches to the Glitch SMP server. Players can equip up to two glitches at a time to change gameplay from normal running around to PVP."
website: https://github.com/nu11ified

commands:
  glitch:
    description: Main command for the Glitch SMP plugin
    usage: /<command> <list|view|help> [player]
    permission: glitchsmp.command.glitch
    aliases: [g]
  glitches:
    description: Opens the operator glitch item GUI
    usage: /<command>
    permission: glitchsmp.command.glitches
  withdraw:
    description: Withdraw an equipped glitch back into an item
    usage: /<command> [1|2]
    permission: glitchsmp.command.withdraw

permissions:
  glitchsmp.command.glitch:
    description: Allows use of the /glitch command
    default: true
  glitchsmp.command.glitch.list:
    description: Allows listing available glitches
    default: true
  glitchsmp.command.glitches:
    description: Allows opening the glitches operator GUI
    default: op
  glitchsmp.command.withdraw:
    description: Allows withdrawing equipped glitches
    default: true
